# Generated by Django 4.1.1 on 2022-09-26 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='stockProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_prod', models.CharField(max_length=50)),
                ('cant_prod', models.IntegerField()),
                ('precio_prod', models.FloatField()),
            ],
        ),
    ]
