# Generated by Django 4.1.1 on 2022-10-23 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockproducts',
            name='image_prod',
            field=models.ImageField(default='static/bolso-default.png', upload_to=''),
        ),
    ]
