# Generated by Django 4.1.1 on 2022-10-23 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_stockproducts_image_prod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockproducts',
            name='image_prod',
            field=models.ImageField(upload_to='static'),
        ),
    ]
