# Generated by Django 4.1.1 on 2022-10-24 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0004_alter_stockproducts_image_prod'),
    ]

    operations = [
        migrations.CreateModel(
            name='carrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_prod', models.CharField(max_length=50)),
                ('cant_prod', models.IntegerField()),
                ('precio_prod', models.FloatField()),
            ],
        ),
    ]
