# Generated by Django 4.1.1 on 2022-10-24 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0005_carrito'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrito',
            name='id',
        ),
        migrations.AlterField(
            model_name='carrito',
            name='nom_prod',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
